# Generated by Django 4.0 on 2022-01-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referrer_id',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
